language: ruby
rvm:
  - 1.9.3
env:
  - DB=sqlite
  - DB=mysql
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database hc_test'
  - RAILS_ENV=test bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
script:
  - bundle exec rspec spec