postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: hc_<%= Rails.env %>

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults